apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}       # use git commit policy
  artifacts:
    - image: jagedn/easy-feedback
      context: .
      docker:
        dockerfile: server/Dockerfile
      sync:
        manual:
          - src: 'src/**'
            dest: .
deploy:
  kubectl:
    manifests:
      - server/k8s/*.yaml