apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: google-key
          secret:
            secretName: google-key
      containers:
        - image: "registry.cloud.okteto.net/easy-feedback/app:latest"
          name: app
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: google-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/client_secret.json
            - name: MICRONAUT_SECURITY_OAUTH2_CLIENTS_GOOGLE_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: google
                  key: google_client_secret
            - name: MICRONAUT_SECURITY_OAUTH2_CLIENTS_GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: google
                  key: google_client_id
            - name: EASYFEEDBACK_PATH
              value: /easy-feedback/storage
          volumeMounts:
            - mountPath: /easy-feedback/storage
              name: storage

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: 'storage'

---

apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "sse"
      port: 8080
  selector:
    app: app
