on:
  push:
    branches:
      - master

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 1-5'

  workflow_dispatch:
    inputs:
      message:
        description: 'Mensaje'
        required: false
        default: 'deploy'

name: okteto

jobs:

  devflow:
    runs-on: ubuntu-latest
    env:
      okteto: ${{secrets.OKTETO_TOKEN}}

    steps:
      - name: checkout
        uses: actions/checkout@master
        if: ${{ env.okteto }}

      - name: "Login"
        uses: okteto/login@master
        if: ${{ env.okteto }}
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@master
        if: ${{ env.okteto }}
        with:
          name: easy-feedback

      - name: "Deploy application"
        uses: okteto/apply@master
        if: ${{ env.okteto }}
        with:
          namespace: easy-feedback
          manifest: k8s/k8s.yml

      - name: "Push changes"
        uses: okteto/push@master
        if: ${{ env.okteto }}
        with:
          namespace: easy-feedback
          name: app
