on: [push]

name: okteto

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: "Login"
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@master
        with:
          name: easy-feedback

      - name: "Deploy application"
        uses: okteto/apply@master
        with:
          namespace: easy-feedback
          manifest: k8s/k8s.yaml

      - name: "Push changes"
        uses: okteto/push@master
        with:
          namespace: easy-feedback
          name: app
