on: [push]

name: okteto

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: "Login"
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Push changes"
        uses: okteto/push@master
        with:
          namespace: easy-feedback
          name: app